version: "3"
services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/frontend
    command: npm run dev
    ports:
      - "3000:3000"

  backend:
    build: ./backend
    volumes:
      - ./backend:/backend
    command: uvicorn main:app --reload --host 0.0.0.0
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres

volumes:
  db-data:
